In [1]:
%env DATA_PATH=../../../data
from lib.fit import load_fit_file, get_gps_data, get_camera_starts, get_camera_ends, get_sensor_data
import gpxpy
import pandas as pd
import glob
from tqdm.notebook import tqdm
import plotly.express as px
import plotly.graph_objects as go
import json
import os

DATA_PATH = '../../../data'

env: DATA_PATH=../../../data

# Match

In [2]:
def to_dict(point):
  return {
    'latitude': point.latitude,
    'longitude': point.longitude,
    'elevation': point.elevation,
    'time': point.time
  }

gpx_data = {}
for p in tqdm(glob.glob(f'{DATA_PATH}/archive/gpx/*.gpx')):
    with open(p, 'r') as f:
        gpx = pd.DataFrame([to_dict(p) for p in gpxpy.parse(f).tracks[0].segments[0].points])
        gpx.time = gpx.time.dt.tz_convert(None)
        gpx_data[p.split('/')[-1][:-4]] = gpx

  0%|          | 0/690 [00:00<?, ?it/s]

## GPX-Fit

In [7]:
gps_data = {}
for p in tqdm(glob.glob(f"{DATA_PATH}/archive/*/GMetrix/*.fit")):
  try:
    gps = get_gps_data(load_fit_file(p))
    if gps is None or gps.empty: continue
    gps_data[f"{p.split('/')[-3]}/{p.split('/')[-1]}"] = gps
  except ValueError as e:
    print(f"Error loading {p}, skipping: {e}")

  0%|          | 0/1855 [00:00<?, ?it/s]

Error loading ../../../data/archive/Zuke/GMetrix/2021-10-02-06-56-01.fit, skipping: Errors encountered while decoding FIT file: [RuntimeError('FIT Runtime Error at byte: 514 Invalid local message number')]

In [8]:
for p in tqdm(glob.glob(f'{DATA_PATH}/archive/Drives/SP/fit/*.fit')):
  try:
    gps = get_gps_data(load_fit_file(p))
    if gps is None or gps.empty: continue
    gps_data[f"Drives/SP/{p.split('/')[-1]}"] = gps
  except ValueError as e:
    print(f"Error loading {p}, skipping: {e}")

  0%|          | 0/222 [00:00<?, ?it/s]

Caching archive_Drives_SP_fit_2018-11-18-07-20-45.json
Caching archive_Drives_SP_fit_2018-04-14-08-36-50.json
Caching archive_Drives_SP_fit_2018-04-08-08-57-26.json
Caching archive_Drives_SP_fit_2017-11-11-16-23-33.json
Caching archive_Drives_SP_fit_2018-10-14-09-55-32.json
Caching archive_Drives_SP_fit_2023-12-31-18-00-16.json
Caching archive_Drives_SP_fit_2018-10-22-16-40-49.json
Caching archive_Drives_SP_fit_2018-03-04-19-49-44.json
Caching archive_Drives_SP_fit_2018-10-07-08-28-32.json
Caching archive_Drives_SP_fit_2018-04-08-09-45-44.json
Caching archive_Drives_SP_fit_2018-03-25-12-42-12.json
Caching archive_Drives_SP_fit_2018-10-17-13-00-58.json
Caching archive_Drives_SP_fit_2018-11-18-08-54-55.json
Caching archive_Drives_SP_fit_2017-10-04-13-29-08.json
Caching archive_Drives_SP_fit_2018-11-07-18-11-29.json
Caching archive_Drives_SP_fit_2018-10-17-13-21-37.json
Caching archive_Drives_SP_fit_2018-11-28-02-15-52.json
Caching archive_Drives_SP_fit_2023-12-31-18-07-16.json
Caching archive_Drives_SP_fit_2018-04-15-07-06-14.json
Caching archive_Drives_SP_fit_2018-03-03-07-26-35.json
Caching archive_Drives_SP_fit_2018-11-04-08-31-25.json
Caching archive_Drives_SP_fit_2018-04-08-08-49-56.json
Caching archive_Drives_SP_fit_2017-11-12-05-03-04.json
Caching archive_Drives_SP_fit_2019-02-23-06-41-02.json
Caching archive_Drives_SP_fit_2017-11-12-05-22-35.json
Caching archive_Drives_SP_fit_2018-03-28-16-17-40.json
Caching archive_Drives_SP_fit_2018-11-11-06-26-46.json
Caching archive_Drives_SP_fit_2018-10-07-08-28-40.json
Caching archive_Drives_SP_fit_2018-11-12-15-55-50.json
Caching archive_Drives_SP_fit_2018-11-12-15-47-57.json
Caching archive_Drives_SP_fit_2018-04-15-08-04-35.json
Caching archive_Drives_SP_fit_2018-03-31-08-05-45.json
Caching archive_Drives_SP_fit_2017-11-12-20-52-47.json
Caching archive_Drives_SP_fit_2018-11-07-18-11-10.json
Caching archive_Drives_SP_fit_2018-04-08-09-07-06.json
Caching archive_Drives_SP_fit_2018-04-14-08-36-54.json
Caching archive_Drives_SP_fit_2018-11-28-13-11-49.json
Caching archive_Drives_SP_fit_2018-11-12-15-48-44.json
Caching archive_Drives_SP_fit_2017-11-12-20-53-18.json
Caching archive_Drives_SP_fit_2018-04-15-08-54-45.json
Caching archive_Drives_SP_fit_2018-11-18-08-55-07.json
Caching archive_Drives_SP_fit_2018-10-07-07-40-34.json
Caching archive_Drives_SP_fit_2018-03-28-15-59-36.json
Caching archive_Drives_SP_fit_2018-03-28-16-04-55.json
Caching archive_Drives_SP_fit_2018-11-18-07-33-49.json
Caching archive_Drives_SP_fit_2018-11-07-02-04-39.json
Caching archive_Drives_SP_fit_2017-10-04-13-26-46.json
Caching archive_Drives_SP_fit_2017-11-13-08-41-21.json
Caching archive_Drives_SP_fit_2018-03-03-07-57-46.json
Caching archive_Drives_SP_fit_2018-04-15-19-07-34.json
Caching archive_Drives_SP_fit_2018-05-07-09-45-29.json
Caching archive_Drives_SP_fit_2024-01-01-00-13-07.json
Caching archive_Drives_SP_fit_2018-10-07-14-54-12.json
Caching archive_Drives_SP_fit_2017-11-09-21-17-47.json
Caching archive_Drives_SP_fit_2018-10-14-09-25-57.json
Caching archive_Drives_SP_fit_2018-04-15-19-27-07.json
Caching archive_Drives_SP_fit_2017-10-27-23-05-17.json
Caching archive_Drives_SP_fit_2018-11-11-06-50-44.json
Caching archive_Drives_SP_fit_2018-03-28-15-40-57.json
Caching archive_Drives_SP_fit_2018-11-27-19-32-45.json
Caching archive_Drives_SP_fit_2018-04-15-07-21-12.json
Caching archive_Drives_SP_fit_2018-04-15-06-24-14.json
Caching archive_Drives_SP_fit_2018-10-07-08-05-51.json
Caching archive_Drives_SP_fit_2018-11-12-14-52-21.json
Caching archive_Drives_SP_fit_2018-03-03-08-34-31.json
Caching archive_Drives_SP_fit_2018-03-25-13-23-34.json
Caching archive_Drives_SP_fit_2018-11-18-07-24-51.json
Caching archive_Drives_SP_fit_2023-12-31-19-16-32.json
Caching archive_Drives_SP_fit_2018-10-14-08-59-38.json
Caching archive_Drives_SP_fit_2018-04-14-08-13-03.json
Caching archive_Drives_SP_fit_2018-11-11-06-18-07.json
Caching archive_Drives_SP_fit_2018-11-28-13-13-15.json
Caching archive_Drives_SP_fit_2018-04-14-08-22-39.json
Caching archive_Drives_SP_fit_2018-10-17-13-27-06.json
Caching archive_Drives_SP_fit_2018-11-18-09-09-36.json
Caching archive_Drives_SP_fit_2017-10-21-12-33-52.json
Caching archive_Drives_SP_fit_2018-03-31-08-44-08.json
Caching archive_Drives_SP_fit_2018-10-14-09-03-06.json
Caching archive_Drives_SP_fit_2017-10-04-12-10-20.json
Caching archive_Drives_SP_fit_2018-04-14-07-19-07.json
Caching archive_Drives_SP_fit_2018-04-08-09-07-24.json
Caching archive_Drives_SP_fit_2018-11-04-08-02-56.json
Caching archive_Drives_SP_fit_2017-10-04-12-08-23.json
Caching archive_Drives_SP_fit_2017-11-11-21-01-44.json
Caching archive_Drives_SP_fit_2018-03-31-08-05-37.json
Caching archive_Drives_SP_fit_2018-04-14-08-42-34.json
Caching archive_Drives_SP_fit_2018-10-14-08-56-20.json
Caching archive_Drives_SP_fit_2017-10-27-22-22-43.json
Caching archive_Drives_SP_fit_2019-02-25-17-35-39.json
Caching archive_Drives_SP_fit_2017-11-11-17-44-00.json
Caching archive_Drives_SP_fit_2018-11-28-13-14-17.json
Caching archive_Drives_SP_fit_2017-10-22-00-53-35.json
Caching archive_Drives_SP_fit_2018-10-17-13-34-11.json
Caching archive_Drives_SP_fit_2018-11-28-02-15-12.json
Caching archive_Drives_SP_fit_2018-11-07-12-08-55.json
Caching archive_Drives_SP_fit_2018-03-28-15-56-06.json
Caching archive_Drives_SP_fit_2018-04-15-05-43-54.json
Caching archive_Drives_SP_fit_2017-11-11-16-50-41.json
Caching archive_Drives_SP_fit_2019-02-25-17-19-20.json
Caching archive_Drives_SP_fit_2017-10-21-12-39-28.json
Caching archive_Drives_SP_fit_2018-03-25-13-24-47.json
Caching archive_Drives_SP_fit_2018-09-23-10-03-14.json
Caching archive_Drives_SP_fit_2018-11-06-23-17-36.json
Caching archive_Drives_SP_fit_2018-10-07-06-36-13.json
Caching archive_Drives_SP_fit_2018-04-15-08-54-15.json
Caching archive_Drives_SP_fit_2018-10-14-09-01-49.json
Caching archive_Drives_SP_fit_2019-02-23-07-08-53.json
Caching archive_Drives_SP_fit_2017-11-09-21-38-47.json
Caching archive_Drives_SP_fit_2018-11-11-07-18-13.json
Caching archive_Drives_SP_fit_2018-05-07-09-04-34.json
Caching archive_Drives_SP_fit_2018-10-14-09-03-39.json
Caching archive_Drives_SP_fit_2018-11-07-12-26-26.json
Caching archive_Drives_SP_fit_2017-11-12-05-22-29.json
Caching archive_Drives_SP_fit_2018-03-25-11-32-22.json
Caching archive_Drives_SP_fit_2018-04-14-08-35-03.json
Caching archive_Drives_SP_fit_2018-03-31-10-36-51.json
Caching archive_Drives_SP_fit_2018-04-15-05-26-37.json
Caching archive_Drives_SP_fit_2017-11-12-05-37-02.json
Caching archive_Drives_SP_fit_2018-04-08-08-59-32.json
Caching archive_Drives_SP_fit_2018-04-15-21-13-59.json
Caching archive_Drives_SP_fit_2018-10-07-15-26-53.json
Caching archive_Drives_SP_fit_2018-11-11-08-49-12.json
Caching archive_Drives_SP_fit_2018-10-17-13-09-21.json
Caching archive_Drives_SP_fit_2018-03-28-23-37-23.json
Caching archive_Drives_SP_fit_2018-04-14-07-27-21.json
Caching archive_Drives_SP_fit_2017-11-11-16-48-02.json
Caching archive_Drives_SP_fit_2018-03-31-10-47-34.json
Caching archive_Drives_SP_fit_2018-04-14-08-15-43.json
Caching archive_Drives_SP_fit_2018-10-22-16-41-14.json
Caching archive_Drives_SP_fit_2018-11-04-07-58-20.json
Caching archive_Drives_SP_fit_2018-10-14-09-00-41.json
Caching archive_Drives_SP_fit_2018-10-14-10-03-32.json
Caching archive_Drives_SP_fit_2017-10-27-22-16-29.json
Caching archive_Drives_SP_fit_2018-11-11-07-01-08.json
Caching archive_Drives_SP_fit_2018-10-22-16-42-21.json
Caching archive_Drives_SP_fit_2018-11-11-06-25-42.json
Caching archive_Drives_SP_fit_2018-10-17-20-51-53.json
Caching archive_Drives_SP_fit_2018-10-14-07-24-11.json
Caching archive_Drives_SP_fit_2017-11-11-21-10-27.json
Caching archive_Drives_SP_fit_2017-11-12-05-57-42.json
Caching archive_Drives_SP_fit_2018-11-07-12-19-15.json
Caching archive_Drives_SP_fit_2018-09-22-21-33-47.json
Caching archive_Drives_SP_fit_2018-04-14-07-36-27.json
Caching archive_Drives_SP_fit_2018-11-18-07-51-55.json
Caching archive_Drives_SP_fit_2018-10-14-08-59-02.json
Caching archive_Drives_SP_fit_2018-11-18-09-09-48.json
Caching archive_Drives_SP_fit_2018-09-23-07-15-29.json
Caching archive_Drives_SP_fit_2018-11-07-18-11-37.json
Caching archive_Drives_SP_fit_2018-09-23-09-46-15.json
Caching archive_Drives_SP_fit_2018-03-25-12-48-32.json
Caching archive_Drives_SP_fit_2017-10-04-12-11-18.json
Caching archive_Drives_SP_fit_2018-04-15-19-34-32.json
Caching archive_Drives_SP_fit_2018-04-15-06-40-57.json
Caching archive_Drives_SP_fit_2018-09-23-06-39-10.json
Caching archive_Drives_SP_fit_2017-10-28-07-06-32.json
Caching archive_Drives_SP_fit_2017-11-11-19-42-53.json
Caching archive_Drives_SP_fit_2017-11-12-05-38-09.json
Caching archive_Drives_SP_fit_2017-11-12-05-36-57.json
Caching archive_Drives_SP_fit_2017-11-12-05-45-46.json
Caching archive_Drives_SP_fit_2018-11-28-12-02-20.json
Caching archive_Drives_SP_fit_2018-11-18-09-02-14.json
Caching archive_Drives_SP_fit_2019-03-01-19-32-49.json
Caching archive_Drives_SP_fit_2018-11-27-20-18-54.json
Caching archive_Drives_SP_fit_2018-04-08-07-50-00.json
Caching archive_Drives_SP_fit_2017-11-12-06-37-41.json
Caching archive_Drives_SP_fit_2018-11-07-02-05-42.json
Caching archive_Drives_SP_fit_2018-11-28-12-05-10.json
Caching archive_Drives_SP_fit_2018-03-31-07-46-11.json
Caching archive_Drives_SP_fit_2018-10-22-16-44-13.json
Caching archive_Drives_SP_fit_2018-11-18-20-33-45.json
Caching archive_Drives_SP_fit_2018-04-08-15-12-13.json
Caching archive_Drives_SP_fit_2018-10-14-09-08-00.json
Caching archive_Drives_SP_fit_2018-03-04-19-21-56.json
Caching archive_Drives_SP_fit_2018-11-07-17-21-32.json
Caching archive_Drives_SP_fit_2017-11-11-16-36-41.json
Caching archive_Drives_SP_fit_2017-11-11-16-30-16.json
Caching archive_Drives_SP_fit_2018-10-14-09-00-20.json
Caching archive_Drives_SP_fit_2023-12-31-18-33-25.json
Caching archive_Drives_SP_fit_2018-10-07-08-05-02.json
Caching archive_Drives_SP_fit_2018-11-12-16-14-03.json
Caching archive_Drives_SP_fit_2018-03-31-08-13-24.json
Caching archive_Drives_SP_fit_2017-10-21-12-43-38.json
Caching archive_Drives_SP_fit_2018-11-11-06-25-21.json
Caching archive_Drives_SP_fit_2018-04-15-19-27-18.json
Caching archive_Drives_SP_fit_2018-11-18-08-55-18.json
Caching archive_Drives_SP_fit_2018-10-07-14-55-14.json
Caching archive_Drives_SP_fit_2017-11-11-23-03-18.json
Caching archive_Drives_SP_fit_2017-11-11-23-04-25.json
Caching archive_Drives_SP_fit_2018-10-07-14-33-15.json
Caching archive_Drives_SP_fit_2019-03-01-19-28-05.json
Caching archive_Drives_SP_fit_2018-11-12-15-54-55.json
Caching archive_Drives_SP_fit_2018-10-17-13-22-37.json
Caching archive_Drives_SP_fit_2018-12-05-01-41-16.json
Caching archive_Drives_SP_fit_2018-09-23-06-37-11.json
Caching archive_Drives_SP_fit_2018-04-08-08-56-49.json
Caching archive_Drives_SP_fit_2018-09-23-05-59-17.json
Caching archive_Drives_SP_fit_2018-11-28-13-14-59.json
Caching archive_Drives_SP_fit_2018-11-18-08-06-30.json
Caching archive_Drives_SP_fit_2018-03-03-07-40-04.json
Caching archive_Drives_SP_fit_2018-09-23-06-38-37.json
Caching archive_Drives_SP_fit_2018-10-07-06-58-08.json
Caching archive_Drives_SP_fit_2017-11-11-23-24-53.json
Caching archive_Drives_SP_fit_2018-11-18-07-34-44.json
Caching archive_Drives_SP_fit_2018-11-18-09-09-17.json
Caching archive_Drives_SP_fit_2018-11-11-06-20-03.json
Caching archive_Drives_SP_fit_2018-11-28-13-15-51.json
Caching archive_Drives_SP_fit_2018-03-28-16-01-52.json
Caching archive_Drives_SP_fit_2018-10-14-08-58-33.json
Caching archive_Drives_SP_fit_2018-11-11-06-24-31.json
Caching archive_Drives_SP_fit_2018-04-15-06-19-12.json
Caching archive_Drives_SP_fit_2018-04-15-21-14-19.json
Caching archive_Drives_SP_fit_2024-01-01-00-46-03.json
Caching archive_Drives_SP_fit_2018-11-04-07-01-49.json
Caching archive_Drives_SP_fit_2018-04-08-15-16-14.json
Caching archive_Drives_SP_fit_2018-04-15-07-16-19.json
Caching archive_Drives_SP_fit_2018-11-04-08-06-36.json
Caching archive_Drives_SP_fit_2018-04-15-08-53-48.json
Caching archive_Drives_SP_fit_2018-11-07-12-24-19.json
Caching archive_Drives_SP_fit_2018-04-08-08-59-20.json
Caching archive_Drives_SP_fit_2017-10-21-13-14-19.json
Caching archive_Drives_SP_fit_2017-11-12-06-10-23.json
Caching archive_Drives_SP_fit_2018-04-14-07-57-24.json

In [9]:
items = sorted(gpx_data.items(), key=lambda x: x[0])
matches = {}
for gpx_key, gpx in tqdm(items):
    gpx_min = gpx.time.min()
    gpx_max = gpx.time.max()
    best = None
    for gps_key, gps in gps_data.items():
        gps_min = gps.utc_timestamp.min()
        gps_max = gps.utc_timestamp.max()
        if gps_min >= gpx_min or gps_max <= gpx_max:
            continue
        
        merged = pd.merge_asof(
            gpx.sort_values('time'), 
            gps.sort_values('utc_timestamp'), 
            left_on='time', 
            right_on='utc_timestamp', 
            direction='nearest'
        )
        score = ((merged.position_lat - merged.latitude) ** 2 + (merged.position_long - merged.longitude) ** 2).mean()
        if score < 1e-7 and (best is None or score < best[1]):
            best = (gps_key, score)
    if best is not None:
        matches[gpx_key] = best[0]

  0%|          | 0/690 [00:00<?, ?it/s]

In [10]:
import json
with open(f'{DATA_PATH}/archive/matches.json', 'w') as f:
    json.dump(matches, f, indent=2)

## GPX-Video

In [40]:
with open(f'{DATA_PATH}/archive/matches.json', 'r') as f:
    fit_matches = json.load(f)

In [8]:
gpx_list = sorted(gpx_data.keys())
gpx_list

['2017_02_19_beichen_inviscid_roll_2',
 '2017_04_02_beichen_inviscid_roll_3',
 '2017_04_02_beichen_inviscid_roll_4',
 '2017_04_09_beichen_inviscid_roll_1',
 '2018_03_03_diamond_zuke_roll_2',
 '2018_03_03_diamond_zuke_roll_3',
 '2018_03_03_diamond_zuke_roll_4',
 '2018_03_03_diamond_zuke_roll_7',
 '2018_03_03_rebecca_kp_roll_3',
 '2018_03_03_rebecca_kp_roll_4',
 '2018_03_03_rebecca_kp_roll_5',
 '2018_03_03_rebecca_kp_roll_7',
 '2018_03_03_sarah_seraph_roll_2',
 '2018_03_03_sarah_seraph_roll_3',
 '2018_03_03_sarah_seraph_roll_5',
 '2018_03_03_sarah_seraph_roll_6',
 '2018_03_03_sarah_seraph_roll_7',
 '2018_03_31_beichen_inviscid_roll_1',
 '2018_03_31_beichen_inviscid_roll_2',
 '2018_03_31_diamond_zuke_roll_1',
 '2018_03_31_rebecca_kp_roll_1',
 '2018_03_31_rebecca_kp_roll_2',
 '2018_03_31_sarah_seraph_roll_2',
 '2018_04_08_beichen_inviscid_roll_1',
 '2018_04_08_beichen_inviscid_roll_3',
 '2018_04_08_diamond_zuke_roll_3',
 '2018_04_08_rebecca_kp_roll_2',
 '2018_04_08_rebecca_kp_roll_3',
 '2018_04_14_beichen_inviscid_roll_1',
 '2018_04_14_beichen_inviscid_roll_2',
 '2018_04_14_beichen_inviscid_roll_3',
 '2018_04_14_beichen_inviscid_roll_4',
 '2018_04_14_rebecca_kp_roll_1',
 '2018_04_14_rebecca_kp_roll_2',
 '2018_04_14_rebecca_kp_roll_3',
 '2018_04_14_rebecca_kp_roll_4',
 '2018_04_14_sarah_seraph_roll_4',
 '2018_04_15_beichen_inviscid_roll_1',
 '2018_04_15_beichen_inviscid_roll_2',
 '2018_04_15_beichen_inviscid_roll_3',
 '2018_04_15_beichen_inviscid_roll_4',
 '2018_04_15_beichen_inviscid_roll_5',
 '2018_04_15_beichen_inviscid_roll_6',
 '2018_04_15_diamond_zuke_roll_1',
 '2018_04_15_diamond_zuke_roll_2',
 '2018_04_15_diamond_zuke_roll_3',
 '2018_04_15_diamond_zuke_roll_4',
 '2018_04_15_rebecca_kp_roll_1',
 '2018_04_15_rebecca_kp_roll_2',
 '2018_04_15_rebecca_kp_roll_3',
 '2018_04_15_rebecca_kp_roll_4',
 '2018_04_15_rebecca_kp_roll_6',
 '2018_09_23_beichen_inviscid_roll_1',
 '2018_09_23_beichen_inviscid_roll_2',
 '2018_09_23_beichen_inviscid_roll_3',
 '2018_09_23_beichen_inviscid_roll_4',
 '2018_09_23_chloe_kp_roll_2',
 '2018_09_23_chloe_kp_roll_3',
 '2018_09_23_chloe_kp_roll_4',
 '2018_09_23_nina_seraph_roll_1',
 '2018_09_23_nina_seraph_roll_2',
 '2018_09_23_nina_seraph_roll_3',
 '2018_09_23_nina_seraph_roll_4',
 '2018_09_23_rebecca_kp_roll_1',
 '2018_10_07_beichen_inviscid_roll_2',
 '2018_10_07_beichen_inviscid_roll_3',
 '2018_10_07_chloe_kp_roll_2',
 '2018_10_07_chloe_kp_roll_3',
 '2018_10_07_nina_seraph_roll_1',
 '2018_10_07_nina_seraph_roll_2',
 '2018_10_07_nina_seraph_roll_3',
 '2018_10_14_beichen_inviscid_roll_2',
 '2018_10_14_beichen_inviscid_roll_3',
 '2018_10_14_chloe_zuke_roll_1',
 '2018_10_14_chloe_zuke_roll_2',
 '2018_10_14_chloe_zuke_roll_3',
 '2018_10_14_rebecca_kp_roll_1',
 '2018_10_14_rebecca_kp_roll_3',
 '2018_11_04_beichen_inviscid_roll_1',
 '2018_11_04_beichen_inviscid_roll_3',
 '2018_11_04_beichen_inviscid_roll_4',
 '2018_11_04_chloe_zuke_roll_2',
 '2018_11_04_chloe_zuke_roll_3',
 '2018_11_04_chloe_zuke_roll_4',
 '2018_11_04_nina_seraph_roll_1',
 '2018_11_04_nina_seraph_roll_2',
 '2018_11_04_rebecca_kp_roll_2',
 '2018_11_04_rebecca_kp_roll_4',
 '2018_11_11_beichen_inviscid_roll_2',
 '2018_11_11_beichen_inviscid_roll_3',
 '2018_11_11_beichen_inviscid_roll_5',
 '2018_11_11_chloe_zuke_roll_1',
 '2018_11_11_chloe_zuke_roll_2',
 '2018_11_11_chloe_zuke_roll_4',
 '2018_11_11_chloe_zuke_roll_5',
 '2018_11_11_chloe_zuke_roll_6',
 '2018_11_11_nina_seraph_roll_1',
 '2018_11_11_nina_seraph_roll_3',
 '2018_11_11_nina_seraph_roll_4',
 '2018_11_11_rebecca_kp_roll_2',
 '2018_11_11_rebecca_kp_roll_3',
 '2018_11_11_rebecca_kp_roll_4',
 '2019_02_23_beichen_inviscid_roll_1',
 '2019_02_23_beichen_inviscid_roll_2',
 '2019_02_23_beichen_inviscid_roll_3',
 '2019_02_23_beichen_inviscid_roll_4',
 '2019_02_23_beichen_inviscid_roll_5',
 '2019_02_23_beichen_inviscid_roll_6',
 '2019_02_23_chloe_zuke_roll_2',
 '2019_02_23_chloe_zuke_roll_3',
 '2019_02_23_chloe_zuke_roll_4',
 '2019_02_23_chloe_zuke_roll_5',
 '2019_02_23_nina_seraph_roll_2',
 '2019_02_23_nina_seraph_roll_3',
 '2019_02_23_nina_seraph_roll_4',
 '2019_02_23_nina_seraph_roll_5',
 '2019_02_23_nina_seraph_roll_6',
 '2019_03_02_nina_seraph_roll_3',
 '2019_03_03_beichen_inviscid_roll_1',
 '2019_03_03_nina_seraph_roll_1',
 '2019_03_03_nina_seraph_roll_2',
 '2019_03_03_nina_seraph_roll_3',
 '2019_03_03_nina_seraph_roll_6',
 '2019_03_03_nina_seraph_roll_8',
 '2019_03_23_chloe_kp_roll_2',
 '2019_03_23_chloe_kp_roll_3',
 '2019_03_23_chloe_zuke_roll_1',
 '2019_03_24_beichen_inviscid_roll_2',
 '2019_03_24_beichen_inviscid_roll_3',
 '2019_03_24_chloe_kp_roll_1',
 '2019_03_24_chloe_kp_roll_2',
 '2019_03_24_chloe_kp_roll_3',
 '2019_03_24_chloe_kp_roll_4',
 '2019_03_24_nina_seraph_roll_3',
 '2019_03_24_nina_seraph_roll_4',
 '2019_04_06_beichen_inviscid_roll_1',
 '2019_04_06_beichen_inviscid_roll_2',
 '2019_04_06_beichen_inviscid_roll_3',
 '2019_04_06_beichen_inviscid_roll_4',
 '2019_04_06_beichen_inviscid_roll_5',
 '2019_04_06_chloe_kp_roll_1',
 '2019_04_06_chloe_kp_roll_3',
 '2019_04_06_chloe_kp_roll_4',
 '2019_04_06_chloe_kp_roll_5',
 '2019_04_06_nina_seraph_roll_1',
 '2019_04_06_nina_seraph_roll_2',
 '2019_04_06_nina_seraph_roll_3',
 '2019_04_06_nina_seraph_roll_4',
 '2019_04_06_nina_seraph_roll_5',
 '2019_04_07_beichen_inviscid_roll_1',
 '2019_04_07_beichen_inviscid_roll_2',
 '2019_04_07_beichen_inviscid_roll_3',
 '2019_04_07_beichen_inviscid_roll_5',
 '2019_04_07_chloe_kp_roll_1',
 '2019_04_07_chloe_kp_roll_2',
 '2019_04_07_chloe_kp_roll_3',
 '2019_04_07_chloe_kp_roll_4',
 '2019_04_07_chloe_kp_roll_5',
 '2019_04_07_nina_seraph_roll_1',
 '2019_04_07_nina_seraph_roll_2',
 '2019_04_07_nina_seraph_roll_3',
 '2019_04_07_nina_seraph_roll_4',
 '2019_09_28_cynthia_zuke_roll_3',
 '2019_09_28_hvn_zuke_roll_2',
 '2019_09_28_nina_inviscid_roll_1',
 '2019_09_28_nina_inviscid_roll_3',
 '2019_10_05_chloe_kp_roll_2',
 '2019_10_05_chloe_kp_roll_4',
 '2019_10_05_cynthia_zuke_roll_1',
 '2019_10_05_cynthia_zuke_roll_3',
 '2019_10_05_gloria_seraph_roll_1',
 '2019_10_05_gloria_seraph_roll_3',
 '2019_10_05_nina_inviscid_roll_2',
 '2019_10_05_nina_inviscid_roll_4',
 '2019_10_06_cynthia_zuke_roll_1',
 '2019_10_06_cynthia_zuke_roll_3',
 '2019_10_06_gloria_seraph_roll_1',
 '2019_10_06_gloria_seraph_roll_2',
 '2019_10_06_gloria_seraph_roll_4',
 '2019_10_06_gloria_seraph_roll_5',
 '2019_10_06_hvn_zuke_roll_4',
 '2019_10_06_hvn_zuke_roll_5',
 '2019_10_13_chloe_kp_roll_2',
 '2019_10_13_chloe_kp_roll_3',
 '2019_10_13_cynthia_zuke_roll_1',
 '2019_10_13_cynthia_zuke_roll_2',
 '2019_10_13_cynthia_zuke_roll_4',
 '2019_10_13_nina_inviscid_roll_1',
 '2019_10_13_nina_inviscid_roll_3',
 '2019_10_13_nina_inviscid_roll_4',
 '2019_10_19_nina_seraph_roll_1_NOGPS',
 '2019_10_19_nina_seraph_roll_2',
 '2019_10_19_nina_seraph_roll_3',
 '2019_10_19_nina_seraph_roll_4',
 '2019_10_19_nina_seraph_roll_5',
 '2019_10_20_cynthia_zuke_roll_1',
 '2019_10_20_cynthia_zuke_roll_2',
 '2019_10_20_cynthia_zuke_roll_3',
 '2019_10_20_gloria_inviscid_roll_1',
 '2019_10_20_gloria_inviscid_roll_3',
 '2019_10_20_gloria_inviscid_roll_4',
 '2019_10_20_gloria_inviscid_roll_5',
 '2019_10_20_gloria_inviscid_roll_6',
 '2019_10_20_nina_seraph_roll_2',
 '2019_10_20_nina_seraph_roll_4',
 '2019_10_20_nina_seraph_roll_5',
 '2019_10_20_nina_seraph_roll_6',
 '2019_10_26_chloe_kp_roll_1',
 '2019_10_26_chloe_kp_roll_3',
 '2019_10_26_gloria_inviscid_roll_1',
 '2019_10_26_gloria_inviscid_roll_2',
 '2019_10_26_hvn_zuke_roll_1',
 '2019_10_26_hvn_zuke_roll_2',
 '2019_10_26_hvn_zuke_roll_3',
 '2019_10_26_hvn_zuke_roll_4',
 '2019_10_26_nina_seraph_roll_2',
 '2019_10_26_nina_seraph_roll_3',
 '2019_10_26_nina_seraph_roll_4',
 '2019_11_02_chloe_kp_roll_3',
 '2019_11_02_gloria_inviscid_roll_1',
 '2019_11_02_gloria_inviscid_roll_2',
 '2019_11_02_hvn_zuke_roll_1',
 '2019_11_02_hvn_zuke_roll_2',
 '2019_11_02_nina_seraph_roll_3',
 '2019_11_03_chloe_kp_roll_1',
 '2019_11_03_chloe_kp_roll_3',
 '2019_11_03_chloe_kp_roll_4',
 '2019_11_03_chloe_kp_roll_5',
 '2019_11_03_cynthia_zuke_roll_1',
 '2019_11_03_cynthia_zuke_roll_2',
 '2019_11_03_cynthia_zuke_roll_3',
 '2019_11_03_cynthia_zuke_roll_5',
 '2019_11_03_cynthia_zuke_roll_6',
 '2019_11_03_gloria_inviscid_roll_1',
 '2019_11_03_gloria_inviscid_roll_4',
 '2019_11_03_gloria_inviscid_roll_5',
 '2019_11_03_nina_seraph_roll_2',
 '2019_11_03_nina_seraph_roll_3',
 '2019_11_03_nina_seraph_roll_4',
 '2019_11_03_nina_seraph_roll_6',
 '2019_11_10_chloe_kp_roll_1',
 '2019_11_10_chloe_kp_roll_2',
 '2019_11_10_chloe_kp_roll_3',
 '2019_11_10_chloe_kp_roll_4',
 '2019_11_10_cynthia_zuke_roll_1',
 '2019_11_10_cynthia_zuke_roll_3',
 '2019_11_10_gloria_inviscid_roll_2',
 '2019_11_10_gloria_inviscid_roll_3',
 '2019_11_10_gloria_inviscid_roll_4',
 '2019_11_10_hvn_zuke_roll_2',
 '2019_11_10_nina_seraph_roll_1',
 '2019_11_10_nina_seraph_roll_2',
 '2019_11_10_nina_seraph_roll_3',
 '2019_11_10_nina_seraph_roll_4',
 '2021_03_21_Cynthia_seraph_roll_1',
 '2021_03_21_Cynthia_seraph_roll_2',
 '2021_03_21_Cynthia_seraph_roll_3',
 '2021_03_21_Cynthia_seraph_roll_4',
 '2021_03_27_Cynthia_seraph_roll_1',
 '2021_03_27_Cynthia_seraph_roll_2',
 '2021_03_27_Cynthia_seraph_roll_3',
 '2021_03_27_Cynthia_seraph_roll_4',
 '2021_03_27_Cynthia_seraph_roll_5',
 '2021_03_27_Cynthia_seraph_roll_6',
 '2021_04_04_Cynthia_Seraph_Roll_1',
 '2021_04_04_Cynthia_Seraph_Roll_2',
 '2021_04_04_Cynthia_Seraph_Roll_3',
 '2021_04_04_Cynthia_Seraph_Roll_4',
 '2021_04_04_Cynthia_Seraph_Roll_5',
 '2021_04_04_Cynthia_Seraph_Roll_6',
 '2021_04_04_Cynthia_Seraph_Roll_7',
 '2021_04_04_Cynthia_Seraph_Roll_8',
 '2021_04_04_Cynthia_Seraph_Roll_9',
 '2021_04_17_Claire_Zuke_roll_1',
 '2021_04_17_Claire_Zuke_roll_2',
 '2021_04_17_Claire_Zuke_roll_3',
 '2021_04_17_Cynthia_Seraph_roll_3',
 '2021_04_17_Cynthia_Seraph_roll_4',
 '2021_04_17_Cynthia_Seraph_roll_5',
 '2021_04_24_Claire_zuke_roll_1',
 '2021_04_24_Claire_zuke_roll_2',
 '2021_04_24_Claire_zuke_roll_3',
 '2021_04_24_Claire_zuke_roll_4',
 '2021_04_24_Claire_zuke_roll_5',
 '2021_04_24_Cynthia_seraph_roll_1',
 '2021_04_24_Cynthia_seraph_roll_2',
 '2021_04_24_Cynthia_seraph_roll_3',
 '2021_04_24_Cynthia_seraph_roll_5',
 '2021_04_24_Cynthia_seraph_roll_6',
 '2021_04_24_Cynthia_seraph_roll_7',
 '2021_09_19_avi_inviscid_roll_2',
 '2021_09_19_chloe_kp_roll_1',
 '2021_09_19_chloe_kp_roll_2',
 '2021_09_19_gloria_zuke_roll_1',
 '2021_09_19_gloria_zuke_roll_2',
 '2021_09_19_gloria_zuke_roll_3',
 '2021_09_19_melina_seraph_roll_2',
 '2021_09_25_avi_inviscid_roll_1',
 '2021_09_25_avi_inviscid_roll_2',
 '2021_09_25_avi_inviscid_roll_3',
 '2021_09_25_gloria_zuke_roll_1',
 '2021_09_25_lara_kp_roll_1',
 '2021_09_25_lara_kp_roll_2',
 '2021_09_25_melina_seraph_roll_1',
 '2021_09_25_melina_seraph_roll_2',
 '2021_09_25_melina_seraph_roll_3',
 '2021_10_02_gloria_zuke_roll_1',
 '2021_10_02_gloria_zuke_roll_2',
 '2021_10_02_gloria_zuke_roll_3',
 '2021_10_02_lara_kp_roll_1',
 '2021_10_02_lara_kp_roll_3',
 '2021_10_02_melina_seraph_roll_1',
 '2021_10_02_melina_seraph_roll_2',
 '2021_10_02_melina_seraph_roll_3',
 '2021_10_10_avi_inviscid_roll_1',
 '2021_10_10_avi_inviscid_roll_2',
 '2021_10_10_chloe_kp_roll_1',
 '2021_10_10_chloe_kp_roll_2',
 '2021_10_10_cynthia_seraph_roll_1',
 '2021_10_10_cynthia_seraph_roll_2',
 '2021_10_10_gloria_zuke_roll_2',
 '2021_10_30_chloe_kp_roll_1',
 '2021_10_30_chloe_kp_roll_2',
 '2021_10_30_cynthia_seraph_roll_1',
 '2021_10_30_cynthia_seraph_roll_2',
 '2021_10_30_cynthia_seraph_roll_3',
 '2021_10_30_gloria_zuke_roll_1',
 '2021_10_30_gloria_zuke_roll_2',
 '2021_11_06_avi_inviscid_roll_3',
 '2021_11_06_chloe_kp_roll_1',
 '2021_11_06_chloe_kp_roll_2',
 '2021_11_06_chloe_kp_roll_3',
 '2021_11_06_gloria_zuke_roll_2',
 '2021_11_06_gloria_zuke_roll_3',
 '2021_11_06_melina_seraph_roll_2',
 '2021_11_07_avi_inviscid_roll_1',
 '2021_11_07_avi_inviscid_roll_2',
 '2021_11_07_avi_inviscid_roll_3',
 '2021_11_07_avi_inviscid_roll_4',
 '2021_11_07_cynthia_seraph_roll_1',
 '2021_11_07_cynthia_seraph_roll_10',
 '2021_11_07_cynthia_seraph_roll_11',
 '2021_11_07_cynthia_seraph_roll_12',
 '2021_11_07_cynthia_seraph_roll_2',
 '2021_11_07_cynthia_seraph_roll_3',
 '2021_11_07_cynthia_seraph_roll_7',
 '2021_11_07_cynthia_seraph_roll_8',
 '2021_11_07_cynthia_seraph_roll_9',
 '2021_11_07_lara_kp_roll_1',
 '2021_11_07_lara_kp_roll_2',
 '2021_11_07_lara_kp_roll_3',
 '2021_11_07_lara_kp_roll_4',
 '2021_11_07_lara_kp_roll_5',
 '2021_11_07_lara_kp_roll_8',
 '2021_11_14_chloe_kp_roll_1',
 '2021_11_14_chloe_kp_roll_2',
 '2021_11_14_chloe_kp_roll_3',
 '2021_11_14_chloe_kp_roll_4',
 '2021_11_14_chloe_kp_roll_5',
 '2021_11_14_chloe_kp_roll_6',
 '2021_11_14_cynthia_seraph_roll_1',
 '2021_11_14_cynthia_seraph_roll_2',
 '2021_11_14_cynthia_seraph_roll_3',
 '2021_11_14_cynthia_seraph_roll_4',
 '2021_11_14_cynthia_seraph_roll_5',
 '2021_11_14_cynthia_seraph_roll_6',
 '2021_11_21_avi_inviscid_roll_4',
 '2021_11_21_avi_inviscid_roll_5',
 '2021_11_21_lara_kp_roll_1',
 '2021_11_21_lara_kp_roll_2',
 '2021_11_21_lara_kp_roll_3',
 '2021_11_21_lara_kp_roll_5',
 '2022_02_27_chloe_kp_roll_1',
 '2022_02_27_chloe_kp_roll_2',
 '2022_02_27_chloe_kp_roll_3',
 '2022_02_27_gloria_zuke_roll_1',
 '2022_02_27_gloria_zuke_roll_2',
 '2022_02_27_gloria_zuke_roll_3',
 '2022_02_27_gloria_zuke_roll_4',
 '2022_02_27_melina_seraph_roll_1',
 '2022_02_27_melina_seraph_roll_2',
 '2022_02_27_melina_seraph_roll_3',
 '2022_02_27_melina_seraph_roll_4',
 '2022_03_19_avi_inviscid_roll_2',
 '2022_03_19_avi_inviscid_roll_3',
 '2022_03_19_chloe_kp_roll_1',
 '2022_03_19_chloe_kp_roll_3',
 '2022_03_19_cynthia_seraph_roll_1',
 '2022_03_19_cynthia_seraph_roll_2',
 '2022_03_19_cynthia_seraph_roll_3',
 '2022_03_19_gloria_zuke_roll_3',
 '2022_04_02_avi_inviscid_roll_2',
 '2022_04_02_avi_inviscid_roll_3',
 '2022_04_02_avi_inviscid_roll_4',
 '2022_04_02_cynthia_seraph_roll_1',
 '2022_04_02_gloria_zuke_roll_1',
 '2022_04_02_gloria_zuke_roll_2',
 '2022_04_02_gloria_zuke_roll_3',
 '2022_04_02_lara_kp_roll_1',
 '2022_04_02_lara_kp_roll_2',
 '2022_04_02_lara_kp_roll_3',
 '2022_04_02_lara_kp_roll_4',
 '2022_04_02_lara_kp_roll_5',
 '2022_04_02_melina_seraph_roll_3',
 '2022_04_02_melina_seraph_roll_4',
 '2022_09_17_avi_inviscid_roll_1',
 '2022_09_17_avi_inviscid_roll_2',
 '2022_09_17_avi_inviscid_roll_3',
 '2022_09_17_avi_inviscid_roll_4',
 '2022_09_17_avi_inviscid_roll_6',
 '2022_09_17_lara_kp_roll_1',
 '2022_09_17_lara_kp_roll_2',
 '2022_09_17_lara_kp_roll_3',
 '2022_09_17_lara_kp_roll_4',
 '2022_09_17_lara_kp_roll_6',
 '2022_09_17_melina_seraph_roll_1',
 '2022_09_17_melina_seraph_roll_2',
 '2022_09_17_melina_seraph_roll_3',
 '2022_09_17_melina_seraph_roll_4',
 '2022_09_17_melina_seraph_roll_6',
 '2022_09_18_cynthia_seraph_roll_1',
 '2022_09_18_cynthia_seraph_roll_2',
 '2022_09_18_cynthia_seraph_roll_3',
 '2022_09_18_cynthia_seraph_roll_4',
 '2022_09_18_lara_kp_roll_1',
 '2022_09_18_lara_kp_roll_2',
 '2022_09_18_lara_kp_roll_3',
 '2022_09_18_lara_kp_roll_4',
 '2022_09_24_avi_inviscid_roll_1',
 '2022_09_24_avi_inviscid_roll_2',
 '2022_09_24_cynthia_seraph_roll_1',
 '2022_09_24_cynthia_seraph_roll_2',
 '2022_09_24_cynthia_seraph_roll_3',
 '2022_09_24_lara_kp_roll_1',
 '2022_09_24_lara_kp_roll_3',
 '2022_09_24_natalie_zuke_roll_1',
 '2022_09_24_natalie_zuke_roll_2',
 '2022_10_08_avi_inviscid_roll_1',
 '2022_10_08_avi_inviscid_roll_2',
 '2022_10_08_avi_inviscid_roll_3',
 '2022_10_08_avi_inviscid_roll_4',
 '2022_10_08_lara_kp_roll_1',
 '2022_10_08_lara_kp_roll_2',
 '2022_10_08_lara_kp_roll_3',
 '2022_10_08_lara_kp_roll_4',
 '2022_10_08_melina_seraph_roll_1',
 '2022_10_08_melina_seraph_roll_2',
 '2022_10_08_melina_seraph_roll_3',
 '2022_10_08_natalie_zuke_roll_1',
 '2022_10_08_natalie_zuke_roll_2',
 '2022_10_08_natalie_zuke_roll_3',
 '2022_10_09_avi_inviscid_roll_1',
 '2022_10_09_avi_inviscid_roll_3',
 '2022_10_09_avi_inviscid_roll_5',
 '2022_10_09_cynthia_seraph_roll_1',
 '2022_10_09_cynthia_seraph_roll_2',
 '2022_10_09_cynthia_seraph_roll_3',
 '2022_10_09_cynthia_seraph_roll_4',
 '2022_10_09_cynthia_seraph_roll_5',
 '2022_10_09_lara_kp_roll_2',
 '2022_10_09_natalie_zuke_roll_1',
 '2022_10_09_natalie_zuke_roll_2',
 '2022_10_09_natalie_zuke_roll_3',
 '2022_10_09_natalie_zuke_roll_4',
 '2022_10_09_natalie_zuke_roll_5',
 '2022_10_29_lara_kp_roll_1',
 '2022_10_29_lara_kp_roll_2',
 '2022_10_29_natalie_zuke_roll_2',
 '2022_11_13_avi_inviscid_roll_1',
 '2022_11_13_avi_inviscid_roll_4',
 '2022_11_13_avi_inviscid_roll_5',
 '2022_11_13_avi_inviscid_roll_6',
 '2022_11_13_melina_seraph_roll_1',
 '2022_11_13_melina_seraph_roll_4',
 '2022_11_5_cynthia_seraph_roll_3',
 '2023_02_11_avi_inviscid_roll_1',
 '2023_02_11_avi_inviscid_roll_2',
 '2023_02_11_avi_inviscid_roll_3',
 '2023_02_11_cynthia_seraph_roll_2',
 '2023_02_11_cynthia_seraph_roll_3',
 '2023_02_11_lara_kp_roll_1',
 '2023_02_11_lara_kp_roll_2',
 '2023_02_12_avi_inviscid_roll_3',
 '2023_02_12_avi_inviscid_roll_4',
 '2023_02_12_avi_inviscid_roll_5',
 '2023_02_12_melina_seraph_roll_2',
 '2023_02_12_melina_seraph_roll_3',
 '2023_02_12_melina_seraph_roll_4',
 '2023_02_12_melina_seraph_roll_5',
 '2023_02_12_natalie_zuke_roll_1',
 '2023_02_12_natalie_zuke_roll_2',
 '2023_02_12_natalie_zuke_roll_3',
 '2023_02_12_natalie_zuke_roll_4',
 '2023_02_12_natalie_zuke_roll_5',
 '2023_02_19_avi_inviscid_roll_1',
 '2023_02_19_cynthia_seraph_roll_1',
 '2023_02_19_lara_kp_roll_1',
 '2023_02_19_natalie_zuke_roll_1',
 '2023_02_25_cynthia_seraph_roll_1',
 '2023_02_25_cynthia_seraph_roll_2',
 '2023_02_25_cynthia_seraph_roll_3',
 '2023_02_25_cynthia_seraph_roll_4',
 '2023_02_25_cynthia_seraph_roll_5',
 '2023_02_25_cynthia_seraph_roll_6',
 '2023_02_25_cynthia_seraph_roll_7',
 '2023_02_25_cynthia_seraph_roll_8',
 '2023_02_25_lara_kp_roll_1',
 '2023_02_25_lara_kp_roll_2',
 '2023_02_25_lara_kp_roll_4',
 '2023_02_25_lara_kp_roll_5',
 '2023_02_25_natalie_zuke_roll_1',
 '2023_02_25_natalie_zuke_roll_2',
 '2023_02_25_natalie_zuke_roll_4',
 '2023_02_25_natalie_zuke_roll_5',
 '2023_02_25_natalie_zuke_roll_6',
 '2023_02_25_natalie_zuke_roll_7',
 '2023_02_25_natalie_zuke_roll_8',
 '2023_02_26_avi_inviscid_roll_1',
 '2023_02_26_avi_inviscid_roll_2',
 '2023_02_26_avi_inviscid_roll_3',
 '2023_02_26_avi_inviscid_roll_4',
 '2023_02_26_avi_inviscid_roll_5',
 '2023_02_26_cynthia_seraph_roll_2',
 '2023_02_26_cynthia_seraph_roll_3',
 '2023_02_26_cynthia_seraph_roll_4',
 '2023_02_26_cynthia_seraph_roll_5',
 '2023_02_26_cynthia_seraph_roll_6',
 '2023_02_26_lara_kp_roll_1',
 '2023_02_26_lara_kp_roll_2',
 '2023_02_26_lara_kp_roll_3',
 '2023_02_26_lara_kp_roll_5',
 '2023_02_26_lara_kp_roll_6',
 '2023_02_26_natalie_zuke_roll_2',
 '2023_02_26_natalie_zuke_roll_3',
 '2023_02_26_natalie_zuke_roll_4',
 '2023_02_26_natalie_zuke_roll_5',
 '2023_02_26_natalie_zuke_roll_6',
 '2023_03_18_avi_zuke_roll_1',
 '2023_03_18_avi_zuke_roll_2',
 '2023_03_18_avi_zuke_roll_3',
 '2023_03_18_avi_zuke_roll_4',
 '2023_03_18_avi_zuke_roll_5',
 '2023_03_18_cynthia_seraph_roll_2',
 '2023_03_18_cynthia_seraph_roll_4',
 '2023_03_18_cynthia_seraph_roll_5',
 '2023_03_18_melina_inviscid_roll_1',
 '2023_03_18_melina_inviscid_roll_2',
 '2023_03_18_melina_inviscid_roll_3',
 '2023_03_26_lara_kp_roll_1',
 '2023_03_26_lara_kp_roll_2',
 '2023_03_26_lara_kp_roll_3',
 '2023_03_26_melina_inviscid_roll_2',
 '2023_03_26_melina_inviscid_roll_3',
 '2023_03_26_natalie_zuke_roll_2',
 '2023_03_26_natalie_zuke_roll_3',
 '2023_04_02_avi_zuke_roll_2',
 '2023_04_02_avi_zuke_roll_3',
 '2023_04_02_avi_zuke_roll_4',
 '2023_04_02_avi_zuke_roll_6',
 '2023_04_02_avi_zuke_roll_8',
 '2023_04_02_cynthia_seraph_roll_2',
 '2023_04_02_cynthia_seraph_roll_6',
 '2023_04_02_cynthia_seraph_roll_8',
 '2023_04_02_melina_inviscid_roll_1',
 '2023_04_02_melina_inviscid_roll_2',
 '2023_04_02_melina_inviscid_roll_4',
 '2023_04_02_melina_inviscid_roll_5',
 '2023_04_02_melina_inviscid_roll_7',
 '2023_09_16_ivania_kp_roll_2',
 '2023_09_16_ivania_kp_roll_3',
 '2023_09_16_ivania_kp_roll_4',
 '2023_09_16_ivania_kp_roll_7',
 '2023_09_16_natalie_seraph_roll_1',
 '2023_09_16_natalie_seraph_roll_2',
 '2023_09_16_natalie_seraph_roll_3',
 '2023_09_16_natalie_seraph_roll_4',
 '2023_09_16_natalie_seraph_roll_5',

In [9]:
GDRIVE_PATH = '/home/yusuf/cmu/etc/mnt/srs'

In [55]:
def get_rd(name: str):
  year, month = name.split('_')[:2]
  year, month = int(year), int(month)
  
  return (year % 100) if month < 5 else ((year + 1) % 100)

In [ ]:
def match_gpx(name: str):
  # TODO: crotch cams?, raw videos?
  year, month, day, driver, buggy, _, roll = name.split('_')[:7]
  year, month, day, roll = int(year), int(month), int(day), int(roll)
  rd = get_rd(name)
  match rd:
    case 24:
      # TODO: add last few days of 2024
      date_str = f"{month}／{day:02d}／{year}"
      if month == 9 and day == 30 and buggy == 'inviscid':
        buggy = 'invisid'
      if month == 2 and day == 24 and buggy == 'zuke' and roll == 1:
        day = 26
      if month == 9 and day == 30 and buggy == 'zuke' and roll >= 5:
        p = f"Raceday '24/Data/Rolls Documentation/{date_str}/{driver}/{year}_{month:02d}_{day:02d}_{driver}_{buggy}_roll{roll}.mp4"
      else:
        p = f"Raceday '24/Data/Rolls Documentation/{date_str}/{driver}/{year}_{month:02d}_{day:02d}_{driver}_{buggy}_roll_{roll}.mp4"
  
    case 23:
      if month == 10:
        date_str = f"{month}／{day:02d}／{year}"
        date_name_str = f"{year}_{month}_{day:02d}"
      else:
        date_str = f"{month}／{day}／{year}"
        if month in (11, 2) and not (month == 2 and day == 26 and buggy != 'inviscid'):
            date_name_str = f"{year}_{month}_{day}"
        else: 
          date_name_str = f"{year}_{month:02d}_{day:02d}"
      if month == 4 and day == 8:
        date_str = "4／8／23"
      if month == 2 and day == 26 and buggy == 'kp' and roll in (2, 3):
        p = f"Raceday '23/Data/Rolls Documentation/{date_str}/{driver}/{date_name_str}_{driver}_{buggy}_roll{roll}.mp4"   
      else:
        p = f"Raceday '23/Data/Rolls Documentation/{date_str}/{driver}/{date_name_str}_{driver}_{buggy}_roll_{roll}.mp4"
  
    case 22:
      date_str = f"{month}／{day}／{year}"
      date_name_str = f"{year}_{month:02d}_{day:02d}"
      if month == 9 and day == 19:
        if buggy == 'inviscid': 
          buggy = 'invicid'
        end_str = f"{roll}"
      else: 
        end_str = f"roll_{roll}"
      
      if month == 11 and day in (6, 7, 21) or (month == 4 and day == 2):
        if month == 4 and day == 2 and buggy == 'seraph':
          driver_folder = 'Cynthia ／ Melina'
        else:
          driver_folder = driver.capitalize()
      else:
        driver_folder = driver
      p = f"Past Raceday Folders/Raceday '22/Data/Rolls Documentation/{date_str}/{driver_folder}/{date_name_str}_{driver}_{buggy}_{end_str}.mp4"
 
    case 21:
      if month == 4 and day == 4:
        p = f"Past Raceday Folders/Raceday '21/Data/Virb Videos/{month:02d}-{day:02d}/{year}_{month:02d}_{day:02d}_{driver}_{buggy.capitalize()}_Roll_{roll}.mp4"
      else:
        p = f"Past Raceday Folders/Raceday '21/Data/Virb Videos/{month:02d}-{day:02d}/{year}_{month:02d}_{day:02d}_{driver}_{buggy}_roll_{roll}.mp4"
    
    case 20:
      p = f"Past Raceday Folders/Raceday '20/Data/Virb Videos/{month:02d}-{day:02d}/{year}_{month:02d}_{day:02d}_{driver}_{buggy}_roll_{roll}.mp4"
  
    case 19:
      folder = {
        (9, 23): "Fall Rolls/Sunday 9／23",
        (10, 7): "Fall Rolls/Sunday 10／7",
        (10, 14): "Fall Rolls/Sunday 10／14",
        (11, 4): "Fall Rolls/Sunday 11／4",
        (11, 11): "Fall Rolls/Sunday 11／11",
        (11, 18): "Fall Rolls/Sunday 11／18 MINI RACEDAY !!!!!!",
        (2, 23): "Spring Rolls/Saturday 2／23",
        (3, 2): "Spring Rolls/Saturday 3／02",
        (3, 3): "Spring Rolls/Sunday 3／03",
        (3, 23): "Spring Rolls/Saturday 3／23",
        (3, 24): "Spring Rolls/Sunday 3／24",
        (4, 6): "Spring Rolls/SATURDAY 4／06 TRUCK WEEKEND!!!!!!",
        (4, 7): "Spring Rolls/SUNDAY 4／07 TRUCK WEEKEND PART 2 ELECTRIC TRUCKALOO",
      }[(month, day)]
      if year == 2018: folder += f"/{driver.capitalize()}"
      
      p = f"Past Raceday Folders/Raceday '19/Data/Virb Videos/{folder}/{year}_{month:02d}_{day:02d}_{driver}_{buggy}_roll_{roll}.mp4"
 
    case 18:
      folder = {
        (9, 30): "Fall Rolls 2017/Saturday 9／30",
        (10, 1): "Fall Rolls 2017/Sunday 10／1",
        (10, 9): "Fall Rolls 2017/Saturday 10／9",
        (11, 4): "Fall Rolls 2017/Saturday 11／4",
        (11, 12): "Fall Rolls 2017/Sunday 11／12",
        (3, 3): "Spring Rolls 2018/Saturday 3／3",
        (3, 31): "Spring Rolls 2018/Saturday 3／31",
        (4, 8): "Spring Rolls 2018/Sunday 4／8",
        (4, 14): "Spring Rolls 2018/Saturday 4／14 TRUCK WEEKEND!!!",
        (4, 15): "Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!",
      }[(month, day)]
      
      match (month, day):
        case (3, 3):
          file_name = f"{year}-{month:02d}-{day:02d}_{buggy.upper()}_{driver.upper()}_ROLL_{roll}.mp4"
        case (3, 31) | (4, 8) | (4, 14) | (4, 15):
          file_name = f"{year}_{month:02d}_{day:02d}_{driver}_{buggy}_roll_{roll}.mp4"
        case _:
          print(f"Unknown filename format for {name}")
          return None
        
      p = f"Past Raceday Folders/Raceday '18/Data/Virb Videos/{folder}/{file_name}"
 
    case 17:
      #TODO: some more gpx on drive
      match (month, day):
        case (2, 19):
          folder = "Spring 2017/2_19/2_19_Beichen_Inviscid_Roll2"
          file_name = "2_19_Beichen_Inviscid_Roll2.mp4"
        case (4, 2) | (4, 9):
          folder = f"Spring 2017/{month}_{day}"
          file_name = f"{month:02d}{day:02d}17_{buggy.capitalize()}_{driver.capitalize()}_R{roll}.mp4"
        case _:
          print(f"Unknown filename format for {name}")
          return None
      
      p = f"Past Raceday Folders/Raceday '17/Data (videos, times, etc)/Virb Videos/{folder}/{file_name}"    
  
    case _:
      print(f"Unknown year for {name}")
      return "x"
  if os.path.exists(f"{GDRIVE_PATH}/{p}"):
    return p
  else:
    return None

In [57]:
vid_matches = {name: match_gpx(name) for name in tqdm(gpx_list)}
vid_matches = {k: v for k, v in vid_matches.items() if v}

  0%|          | 0/690 [00:00<?, ?it/s]

2017_02_19_beichen_inviscid_roll_2: Past Raceday Folders/Raceday '17/Data (videos, times, etc)/Virb Videos/Spring 2017/2_19/2_19_Beichen_Inviscid_Roll2/2_19_Beichen_Inviscid_Roll2.mp4
2017_04_02_beichen_inviscid_roll_3: Past Raceday Folders/Raceday '17/Data (videos, times, etc)/Virb Videos/Spring 2017/4_2/040217_Inviscid_Beichen_R3.mp4
2017_04_02_beichen_inviscid_roll_4: Past Raceday Folders/Raceday '17/Data (videos, times, etc)/Virb Videos/Spring 2017/4_2/040217_Inviscid_Beichen_R4.mp4
2017_04_09_beichen_inviscid_roll_1: Past Raceday Folders/Raceday '17/Data (videos, times, etc)/Virb Videos/Spring 2017/4_9/040917_Inviscid_Beichen_R1.mp4
2018_03_03_diamond_zuke_roll_2: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_ZUKE_DIAMOND_ROLL_2.mp4
2018_03_03_diamond_zuke_roll_3: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_ZUKE_DIAMOND_ROLL_3.mp4
2018_03_03_diamond_zuke_roll_4: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_ZUKE_DIAMOND_ROLL_4.mp4
2018_03_03_diamond_zuke_roll_7: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_ZUKE_DIAMOND_ROLL_7.mp4
2018_03_03_rebecca_kp_roll_3: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_KP_REBECCA_ROLL_3.mp4
2018_03_03_rebecca_kp_roll_4: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_KP_REBECCA_ROLL_4.mp4
2018_03_03_rebecca_kp_roll_5: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_KP_REBECCA_ROLL_5.mp4
2018_03_03_rebecca_kp_roll_7: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_KP_REBECCA_ROLL_7.mp4
2018_03_03_sarah_seraph_roll_2: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_SERAPH_SARAH_ROLL_2.mp4
2018_03_03_sarah_seraph_roll_3: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_SERAPH_SARAH_ROLL_3.mp4
2018_03_03_sarah_seraph_roll_5: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_SERAPH_SARAH_ROLL_5.mp4
2018_03_03_sarah_seraph_roll_6: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_SERAPH_SARAH_ROLL_6.mp4
2018_03_03_sarah_seraph_roll_7: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／3/2018-03-03_SERAPH_SARAH_ROLL_7.mp4
2018_03_31_beichen_inviscid_roll_1: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／31/2018_03_31_beichen_inviscid_roll_1.mp4
2018_03_31_beichen_inviscid_roll_2: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／31/2018_03_31_beichen_inviscid_roll_2.mp4
2018_03_31_diamond_zuke_roll_1: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／31/2018_03_31_diamond_zuke_roll_1.mp4
2018_03_31_rebecca_kp_roll_1: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／31/2018_03_31_rebecca_kp_roll_1.mp4
2018_03_31_rebecca_kp_roll_2: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／31/2018_03_31_rebecca_kp_roll_2.mp4
2018_03_31_sarah_seraph_roll_2: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 3／31/2018_03_31_sarah_seraph_roll_2.mp4
2018_04_08_beichen_inviscid_roll_1: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／8/2018_04_08_beichen_inviscid_roll_1.mp4
2018_04_08_beichen_inviscid_roll_3: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／8/2018_04_08_beichen_inviscid_roll_3.mp4
2018_04_08_diamond_zuke_roll_3: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／8/2018_04_08_diamond_zuke_roll_3.mp4
2018_04_08_rebecca_kp_roll_2: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／8/2018_04_08_rebecca_kp_roll_2.mp4
2018_04_08_rebecca_kp_roll_3: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／8/2018_04_08_rebecca_kp_roll_3.mp4
2018_04_14_beichen_inviscid_roll_1: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 4／14 TRUCK WEEKEND!!!/2018_04_14_beichen_inviscid_roll_1.mp4
2018_04_14_beichen_inviscid_roll_2: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 4／14 TRUCK WEEKEND!!!/2018_04_14_beichen_inviscid_roll_2.mp4
2018_04_14_beichen_inviscid_roll_3: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 4／14 TRUCK WEEKEND!!!/2018_04_14_beichen_inviscid_roll_3.mp4
2018_04_14_beichen_inviscid_roll_4: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 4／14 TRUCK WEEKEND!!!/2018_04_14_beichen_inviscid_roll_4.mp4
2018_04_14_rebecca_kp_roll_1: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 4／14 TRUCK WEEKEND!!!/2018_04_14_rebecca_kp_roll_1.mp4
2018_04_14_rebecca_kp_roll_2: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 4／14 TRUCK WEEKEND!!!/2018_04_14_rebecca_kp_roll_2.mp4
2018_04_14_rebecca_kp_roll_3: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 4／14 TRUCK WEEKEND!!!/2018_04_14_rebecca_kp_roll_3.mp4
2018_04_14_rebecca_kp_roll_4: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 4／14 TRUCK WEEKEND!!!/2018_04_14_rebecca_kp_roll_4.mp4
2018_04_14_sarah_seraph_roll_4: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Saturday 4／14 TRUCK WEEKEND!!!/2018_04_14_sarah_seraph_roll_4.mp4
2018_04_15_beichen_inviscid_roll_1: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_beichen_inviscid_roll_1.mp4
2018_04_15_beichen_inviscid_roll_2: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_beichen_inviscid_roll_2.mp4
2018_04_15_beichen_inviscid_roll_3: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_beichen_inviscid_roll_3.mp4
2018_04_15_beichen_inviscid_roll_4: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_beichen_inviscid_roll_4.mp4
2018_04_15_beichen_inviscid_roll_5: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_beichen_inviscid_roll_5.mp4
2018_04_15_beichen_inviscid_roll_6: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_beichen_inviscid_roll_6.mp4
2018_04_15_diamond_zuke_roll_1: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_diamond_zuke_roll_1.mp4
2018_04_15_diamond_zuke_roll_2: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_diamond_zuke_roll_2.mp4
2018_04_15_diamond_zuke_roll_3: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_diamond_zuke_roll_3.mp4
2018_04_15_diamond_zuke_roll_4: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_diamond_zuke_roll_4.mp4
2018_04_15_rebecca_kp_roll_1: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_rebecca_kp_roll_1.mp4
2018_04_15_rebecca_kp_roll_2: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_rebecca_kp_roll_2.mp4
2018_04_15_rebecca_kp_roll_3: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_rebecca_kp_roll_3.mp4
2018_04_15_rebecca_kp_roll_4: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_rebecca_kp_roll_4.mp4
2018_04_15_rebecca_kp_roll_6: Past Raceday Folders/Raceday '18/Data/Virb Videos/Spring Rolls 2018/Sunday 4／15 TRUCK WEEEEEKEND!!!!!/2018_04_15_rebecca_kp_roll_6.mp4
2018_09_23_beichen_inviscid_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Beichen/2018_09_23_beichen_inviscid_roll_1.mp4
2018_09_23_beichen_inviscid_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Beichen/2018_09_23_beichen_inviscid_roll_2.mp4
2018_09_23_beichen_inviscid_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Beichen/2018_09_23_beichen_inviscid_roll_3.mp4
2018_09_23_beichen_inviscid_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Beichen/2018_09_23_beichen_inviscid_roll_4.mp4
2018_09_23_chloe_kp_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Chloe/2018_09_23_chloe_kp_roll_2.mp4
2018_09_23_chloe_kp_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Chloe/2018_09_23_chloe_kp_roll_3.mp4
2018_09_23_chloe_kp_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Chloe/2018_09_23_chloe_kp_roll_4.mp4
2018_09_23_nina_seraph_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Nina/2018_09_23_nina_seraph_roll_1.mp4
2018_09_23_nina_seraph_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Nina/2018_09_23_nina_seraph_roll_2.mp4
2018_09_23_nina_seraph_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Nina/2018_09_23_nina_seraph_roll_3.mp4
2018_09_23_nina_seraph_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Nina/2018_09_23_nina_seraph_roll_4.mp4
2018_09_23_rebecca_kp_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 9／23/Rebecca/2018_09_23_rebecca_kp_roll_1.mp4
2018_10_07_beichen_inviscid_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／7/Beichen/2018_10_07_beichen_inviscid_roll_2.mp4
2018_10_07_beichen_inviscid_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／7/Beichen/2018_10_07_beichen_inviscid_roll_3.mp4
2018_10_07_chloe_kp_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／7/Chloe/2018_10_07_chloe_kp_roll_2.mp4
2018_10_07_chloe_kp_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／7/Chloe/2018_10_07_chloe_kp_roll_3.mp4
2018_10_07_nina_seraph_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／7/Nina/2018_10_07_nina_seraph_roll_1.mp4
2018_10_07_nina_seraph_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／7/Nina/2018_10_07_nina_seraph_roll_2.mp4
2018_10_07_nina_seraph_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／7/Nina/2018_10_07_nina_seraph_roll_3.mp4
2018_10_14_beichen_inviscid_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／14/Beichen/2018_10_14_beichen_inviscid_roll_2.mp4
2018_10_14_beichen_inviscid_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／14/Beichen/2018_10_14_beichen_inviscid_roll_3.mp4
2018_10_14_chloe_zuke_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／14/Chloe/2018_10_14_chloe_zuke_roll_1.mp4
2018_10_14_chloe_zuke_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／14/Chloe/2018_10_14_chloe_zuke_roll_2.mp4
2018_10_14_chloe_zuke_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／14/Chloe/2018_10_14_chloe_zuke_roll_3.mp4
2018_10_14_rebecca_kp_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／14/Rebecca/2018_10_14_rebecca_kp_roll_1.mp4
2018_10_14_rebecca_kp_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 10／14/Rebecca/2018_10_14_rebecca_kp_roll_3.mp4
2018_11_04_beichen_inviscid_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／4/Beichen/2018_11_04_beichen_inviscid_roll_1.mp4
2018_11_04_beichen_inviscid_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／4/Beichen/2018_11_04_beichen_inviscid_roll_3.mp4
2018_11_04_beichen_inviscid_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／4/Beichen/2018_11_04_beichen_inviscid_roll_4.mp4
2018_11_04_chloe_zuke_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／4/Chloe/2018_11_04_chloe_zuke_roll_2.mp4
2018_11_04_chloe_zuke_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／4/Chloe/2018_11_04_chloe_zuke_roll_3.mp4
2018_11_04_chloe_zuke_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／4/Chloe/2018_11_04_chloe_zuke_roll_4.mp4
2018_11_04_nina_seraph_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／4/Nina/2018_11_04_nina_seraph_roll_1.mp4
2018_11_04_nina_seraph_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／4/Nina/2018_11_04_nina_seraph_roll_2.mp4
2018_11_04_rebecca_kp_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／4/Rebecca/2018_11_04_rebecca_kp_roll_2.mp4
2018_11_04_rebecca_kp_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／4/Rebecca/2018_11_04_rebecca_kp_roll_4.mp4
2018_11_11_beichen_inviscid_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Beichen/2018_11_11_beichen_inviscid_roll_2.mp4
2018_11_11_beichen_inviscid_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Beichen/2018_11_11_beichen_inviscid_roll_3.mp4
2018_11_11_beichen_inviscid_roll_5: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Beichen/2018_11_11_beichen_inviscid_roll_5.mp4
2018_11_11_chloe_zuke_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Chloe/2018_11_11_chloe_zuke_roll_1.mp4
2018_11_11_chloe_zuke_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Chloe/2018_11_11_chloe_zuke_roll_2.mp4
2018_11_11_chloe_zuke_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Chloe/2018_11_11_chloe_zuke_roll_4.mp4
2018_11_11_chloe_zuke_roll_5: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Chloe/2018_11_11_chloe_zuke_roll_5.mp4
2018_11_11_chloe_zuke_roll_6: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Chloe/2018_11_11_chloe_zuke_roll_6.mp4
2018_11_11_nina_seraph_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Nina/2018_11_11_nina_seraph_roll_1.mp4
2018_11_11_nina_seraph_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Nina/2018_11_11_nina_seraph_roll_3.mp4
2018_11_11_nina_seraph_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Nina/2018_11_11_nina_seraph_roll_4.mp4
2018_11_11_rebecca_kp_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Rebecca/2018_11_11_rebecca_kp_roll_2.mp4
2018_11_11_rebecca_kp_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Rebecca/2018_11_11_rebecca_kp_roll_3.mp4
2018_11_11_rebecca_kp_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Fall Rolls/Sunday 11／11/Rebecca/2018_11_11_rebecca_kp_roll_4.mp4
2019_02_23_beichen_inviscid_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_beichen_inviscid_roll_1.mp4
2019_02_23_beichen_inviscid_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_beichen_inviscid_roll_2.mp4
2019_02_23_beichen_inviscid_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_beichen_inviscid_roll_3.mp4
2019_02_23_beichen_inviscid_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_beichen_inviscid_roll_4.mp4
2019_02_23_beichen_inviscid_roll_5: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_beichen_inviscid_roll_5.mp4
2019_02_23_beichen_inviscid_roll_6: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_beichen_inviscid_roll_6.mp4
2019_02_23_chloe_zuke_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_chloe_zuke_roll_2.mp4
2019_02_23_chloe_zuke_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_chloe_zuke_roll_3.mp4
2019_02_23_chloe_zuke_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_chloe_zuke_roll_4.mp4
2019_02_23_chloe_zuke_roll_5: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_chloe_zuke_roll_5.mp4
2019_02_23_nina_seraph_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_nina_seraph_roll_2.mp4
2019_02_23_nina_seraph_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_nina_seraph_roll_3.mp4
2019_02_23_nina_seraph_roll_4: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_nina_seraph_roll_4.mp4
2019_02_23_nina_seraph_roll_5: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_nina_seraph_roll_5.mp4
2019_02_23_nina_seraph_roll_6: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 2／23/2019_02_23_nina_seraph_roll_6.mp4
2019_03_02_nina_seraph_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 3／02/2019_03_02_nina_seraph_roll_3.mp4
2019_03_03_beichen_inviscid_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Sunday 3／03/2019_03_03_beichen_inviscid_roll_1.mp4
2019_03_03_nina_seraph_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Sunday 3／03/2019_03_03_nina_seraph_roll_1.mp4
2019_03_03_nina_seraph_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Sunday 3／03/2019_03_03_nina_seraph_roll_2.mp4
2019_03_03_nina_seraph_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Sunday 3／03/2019_03_03_nina_seraph_roll_3.mp4
2019_03_03_nina_seraph_roll_6: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Sunday 3／03/2019_03_03_nina_seraph_roll_6.mp4
2019_03_03_nina_seraph_roll_8: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Sunday 3／03/2019_03_03_nina_seraph_roll_8.mp4
2019_03_23_chloe_kp_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 3／23/2019_03_23_chloe_kp_roll_2.mp4
2019_03_23_chloe_kp_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 3／23/2019_03_23_chloe_kp_roll_3.mp4
2019_03_23_chloe_zuke_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Saturday 3／23/2019_03_23_chloe_zuke_roll_1.mp4
2019_03_24_beichen_inviscid_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Sunday 3／24/2019_03_24_beichen_inviscid_roll_2.mp4
2019_03_24_beichen_inviscid_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Sunday 3／24/2019_03_24_beichen_inviscid_roll_3.mp4
2019_03_24_chloe_kp_roll_1: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Sunday 3／24/2019_03_24_chloe_kp_roll_1.mp4
2019_03_24_chloe_kp_roll_2: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Sunday 3／24/2019_03_24_chloe_kp_roll_2.mp4
2019_03_24_chloe_kp_roll_3: Past Raceday Folders/Raceday '19/Data/Virb Videos/Spring Rolls/Sunday 3／24/2019_03_24_chloe_kp_roll_3.mp4

In [44]:
with open(f'{DATA_PATH}/archive/video_matches.json', 'w') as f:
    json.dump(vid_matches, f, indent=2)

In [60]:
from collections import Counter

fit_year_count = Counter(get_rd(k) for k in fit_matches.keys())
vid_year_count = Counter(get_rd(k) for k in vid_matches.keys())
both_year_count = Counter(get_rd(k) for k in fit_matches.keys() if k in vid_matches)
print(fit_year_count.total(), vid_year_count.total(), both_year_count.total())
sorted(fit_year_count.most_common()), sorted(vid_year_count.most_common()), sorted(both_year_count.most_common())

399 629 372

([(18, 15), (19, 28), (20, 4), (21, 9), (22, 80), (23, 147), (24, 116)],
 [(17, 3),
  (18, 48),
  (19, 66),
  (20, 92),
  (21, 36),
  (22, 114),
  (23, 158),
  (24, 112)],
 [(18, 15), (19, 17), (20, 4), (21, 9), (22, 79), (23, 142), (24, 106)])

In [62]:
total_size = 0
for name, path in tqdm(vid_matches.items()):
    size = os.path.getsize(f"{GDRIVE_PATH}/{path}")
    total_size += size
print(f"Total size: {total_size / 1e9:.2f} GB")

  0%|          | 0/629 [00:00<?, ?it/s]

Total size: 234.78 GB

# Tests

## Calibrate

In [3]:
fit = load_fit_file(f"{DATA_PATH}/archive/tmp/2026-05-03-18-20-56.fit")

Caching archive_tmp_2026-05-03-18-20-56.json

In [7]:
calibration_mesgs = fit['three_d_sensor_calibration_mesgs']
calibration_data = { m['sensor_type']: m for m in calibration_mesgs }
accel_cal = calibration_data['accelerometer']
accel_raw, accel_data, fs = get_sensor_data(accel_cal, fit['accelerometer_data_mesgs'], {'x': 'accel_x', 'y': 'accel_y', 'z': 'accel_z'})
accel_data

                  x         y         z  timestamp
timestamp
71247     -0.013184 -0.068359 -0.996094      71247
71257     -0.013672 -0.066406 -0.995117      71257
71267     -0.013672 -0.063477 -0.994141      71267
71277     -0.014160 -0.060059 -0.994141      71277
71287     -0.016113 -0.053711 -0.993164      71287
71297     -0.017578 -0.047852 -0.991211      71297
71307     -0.017090 -0.047363 -0.991211      71307
71317     -0.016602 -0.048828 -0.992188      71317
71327     -0.015625 -0.051270 -0.993164      71327
71337     -0.014648 -0.053223 -0.994629      71337
71347     -0.014160 -0.055664 -0.995117      71347
71357     -0.013672 -0.060547 -0.995117      71357
71367     -0.014160 -0.064941 -0.994141      71367
71377     -0.014648 -0.068848 -0.993164      71377
71387     -0.014648 -0.068848 -0.992188      71387
71401     -0.013672 -0.066895 -0.993164      71401
71411     -0.013184 -0.065430 -0.995605      71411
71421     -0.012695 -0.065430 -0.996094      71421
71431     -0.012695 -0.064941 -0.994629      71431
71443     -0.013184 -0.062988 -0.993164      71443
71453     -0.013672 -0.061523 -0.992188      71453
71463     -0.013672 -0.061035 -0.992676      71463
71473     -0.013184 -0.062988 -0.993164      71473
71485     -0.012207 -0.066895 -0.994141      71485
71495     -0.012207 -0.070801 -0.995117      71495
71505     -0.012207 -0.071777 -0.994629      71505
71515     -0.013184 -0.070801 -0.994629      71515
71529     -0.013184 -0.069824 -0.994141      71529
71539     -0.012695 -0.064941 -0.993652      71539
71549     -0.012695 -0.060547 -0.993652      71549

## Misc

In [23]:
with open(f"{DATA_PATH}/archive/tmp/2023_04_02_seraph_gpx/2023_04_02_cynthia_seraph_roll_6.gpx") as f:
  gpx = gpxpy.parse(f)
seg = gpx.tracks[0].segments[0]
len(seg.points)

159

In [44]:
def to_dict(point):
  return {
    'latitude': point.latitude,
    'longitude': point.longitude,
    'elevation': point.elevation,
    'time': point.time
  }
gpx_data = pd.DataFrame([to_dict(p) for p in seg.points])
gpx_data.time = gpx_data.time.dt.tz_convert(None)
gpx_data

      latitude  longitude   elevation                time
0    40.441671 -79.941681  298.600006 2023-04-02 12:28:10
1    40.441671 -79.941681  298.600006 2023-04-02 12:28:11
2    40.441654 -79.941688  298.399994 2023-04-02 12:28:12
3    40.441629 -79.941701  298.399994 2023-04-02 12:28:13
4    40.441596 -79.941718  298.200012 2023-04-02 12:28:14
..         ...        ...         ...                 ...
154  40.440617 -79.942895  286.000000 2023-04-02 12:30:44
155  40.440594 -79.942798  286.200012 2023-04-02 12:30:45
156  40.440584 -79.942727  286.399994 2023-04-02 12:30:46
157  40.440571 -79.942639  286.600006 2023-04-02 12:30:47
158  40.440553 -79.942544  286.799988 2023-04-02 12:30:48

[159 rows x 4 columns]

In [26]:
fit_data = {}

for path in tqdm(glob.glob(f"{DATA_PATH}/archive/tmp/2023_04_02_fit/*.fit")):
  fit_data[path] = load_fit_file(path)

  0%|          | 0/24 [00:00<?, ?it/s]

Caching archive_tmp_2023_04_02_fit_2023-04-02-08-47-53.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-27-01.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-07-09-41.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-22-35 (2).json
Caching archive_tmp_2023_04_02_fit_2023-04-02-06-24-26.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-07-50-08.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-06-54-36.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-22-23.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-48-10.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-22-35.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-07-33-43.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-48-24.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-07-34-11.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-07-21-13.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-20-37.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-07-08-04.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-06-21-45.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-22-12.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-06-42-37.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-09-01-56.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-48-25.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-25-05.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-00-56.json
Caching archive_tmp_2023_04_02_fit_2023-04-02-08-01-01.json

In [27]:
for path, data in fit_data.items():
  elapsed = data['session_mesgs'][0]['total_elapsed_time']
  if elapsed < 60: continue
  print(f"{path}: {data['session_mesgs'][0]['total_elapsed_time']}")

../../../data/archive/tmp/2023_04_02_fit/2023-04-02-08-27-01.fit: 406.747
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-07-09-41.fit: 543.957
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-08-22-35 (2).fit: 636.078
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-07-50-08.fit: 369.228
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-06-54-36.fit: 546.33
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-08-22-35.fit: 634.383
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-07-33-43.fit: 1216.193
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-08-48-24.fit: 743.321
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-07-34-11.fit: 485.584
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-07-21-13.fit: 343.863
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-08-20-37.fit: 948.336
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-07-08-04.fit: 582.637
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-06-42-37.fit: 106.204
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-08-48-25.fit: 745.41
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-08-25-05.fit: 108.673
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-08-00-56.fit: 624.574
../../../data/archive/tmp/2023_04_02_fit/2023-04-02-08-01-01.fit: 474.703

In [30]:
gps_data = {path.split("/")[-1]: get_gps_data(data) for path, data in fit_data.items()}
gps_data.keys()

dict_keys(['2023-04-02-08-47-53.fit', '2023-04-02-08-27-01.fit', '2023-04-02-07-09-41.fit', '2023-04-02-08-22-35 (2).fit', '2023-04-02-06-24-26.fit', '2023-04-02-07-50-08.fit', '2023-04-02-06-54-36.fit', '2023-04-02-08-22-23.fit', '2023-04-02-08-48-10.fit', '2023-04-02-08-22-35.fit', '2023-04-02-07-33-43.fit', '2023-04-02-08-48-24.fit', '2023-04-02-07-34-11.fit', '2023-04-02-07-21-13.fit', '2023-04-02-08-20-37.fit', '2023-04-02-07-08-04.fit', '2023-04-02-06-21-45.fit', '2023-04-02-08-22-12.fit', '2023-04-02-06-42-37.fit', '2023-04-02-09-01-56.fit', '2023-04-02-08-48-25.fit', '2023-04-02-08-25-05.fit', '2023-04-02-08-00-56.fit', '2023-04-02-08-01-01.fit'])

In [47]:
def match_points(gpx: pd.DataFrame, gps: pd.DataFrame) -> pd.DataFrame | None:
  if gps is None or gpx is None:
    return None
  gpx_min, gpx_max = gpx.time.min(), gpx.time.max()
  gps_min, gps_max = gps.utc_timestamp.min(), gps.utc_timestamp.max()
  if gpx_max > gps_max or gpx_min < gps_min:
    return None
  
  return pd.merge_asof(
    gpx.sort_values('time'), 
    gps.sort_values('utc_timestamp'), 
    left_on='time', 
    right_on='utc_timestamp', 
    direction='nearest'
  )

In [53]:
gps = gps_data['Inviscid/2021-04-24-08-28-56.fit']
gpx = gpx_data['2021_04_24_Cynthia_seraph_roll_6']

In [54]:
# gps: pd.DataFrame = gps_data[list(gps_data.keys())[1]]
merged: pd.DataFrame = match_points(gpx, gps)
merged

,latitude,longitude,elevation,time,timestamp,position_lat,position_long,enhanced_altitude,enhanced_speed,utc_timestamp,timestamp_ms,heading,velocity,8,9,10,11,12,speed
0,40.440958,-79.941921,285.634003,2021-04-24 12:29:19,23177,40.440956,-79.941921,285.8,1.830,2021-04-24 12:29:19,177,194.13,"[-0.44, -1.77, -0.01]",3,4,5,74,125,1.823897
1,40.440931,-79.941930,285.833984,2021-04-24 12:29:20,24177,40.440924,-79.941933,286.0,3.761,2021-04-24 12:29:20,177,197.07,"[-1.1, -3.59, 0.0]",3,4,5,111,127,3.754744
2,40.440888,-79.941946,286.000000,2021-04-24 12:29:21,25577,40.440864,-79.941957,286.2,4.510,2021-04-24 12:29:21,577,197.27,"[-1.33, -4.3, 0.07]",3,4,5,111,127,4.501533
3,40.440849,-79.941964,286.399994,2021-04-24 12:29:22,25777,40.440856,-79.941960,286.4,4.444,2021-04-24 12:29:22,777,196.53,"[-1.26, -4.26, 0.08]",3,4,5,111,127,4.443152
4,40.440799,-79.941985,286.799988,2021-04-24 12:29:23,27177,40.440788,-79.941989,287.0,6.372,2021-04-24 12:29:23,177,198.20,"[-1.99, -6.05, 0.15]",3,4,5,111,127,6.370644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,40.440380,-79.942712,286.799988,2021-04-24 12:31:48,171776,40.440382,-79.942724,286.8,4.996,2021-04-24 12:31:48,776,104.36,"[4.83, -1.23, 0.25]",3,32,33,97,357,4.990421
126,40.440351,-79.942658,287.000000,2021-04-24 12:31:49,173176,40.440351,-79.942647,287.0,4.896,2021-04-24 12:31:49,176,115.58,"[4.41, -2.11, 0.22]",3,23,23,403,384,4.893731
127,40.440357,-79.942598,287.200012,2021-04-24 12:31:50,174176,40.440358,-79.942587,287.2,4.796,2021-04-24 12:31:50,176,108.33,"[4.55, -1.5, 0.16]",3,20,20,404,384,4.793548
128,40.440365,-79.942543,287.399994,2021-04-24 12:31:51,175076,40.440368,-79.942537,287.4,4.627,2021-04-24 12:31:51,76,100.87,"[4.54, -0.87, 0.14]",3,17,18,351,320,4.624727
129,40.440378,-79.942493,287.399994,2021-04-24 12:31:52,176176,40.440378,-79.942485,287.4,3.719,2021-04-24 12:31:52,176,96.20,"[3.69, -0.4, 0.13]",3,16,16,351,320,3.713893

In [55]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=merged.time, y=merged.elevation, mode='markers', name='gpx elevation'))
fig.add_trace(go.Scatter(x=merged.time, y=merged.enhanced_altitude, mode='markers', name='gps altitude'))
fig.update_layout(title='Elevation vs Altitude', xaxis_title='Time', yaxis_title='Elevation/Altitude')
fig.show()

In [56]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=merged.longitude, y=merged.latitude, 
                         mode='markers', customdata=merged[['timestamp']], 
                         hovertemplate="%{customdata[0]}: (%{x}, %{y})", name='gpx'))
fig.add_trace(go.Scatter(x=merged.position_long, y=merged.position_lat,
                         mode='markers', customdata=merged[['timestamp']], 
                         hovertemplate="%{customdata[0]}: (%{x}, %{y})", name='gps'))
fig.show()

In [33]:
gps_data[list(gps_data.keys())[1]]

,timestamp,position_lat,position_long,enhanced_altitude,enhanced_speed,utc_timestamp,timestamp_ms,heading,velocity,8,9,10,11,12,speed
timestamp,,,,,,,,,,,,,,,
18211,18211,40.441629,-79.941338,323.8,1.797,2023-04-02 12:27:18,211,335.19,"[-0.75, 1.63, -0.34]",17,67,69,94,187,1.826198
18311,18311,40.441630,-79.941347,323.6,1.796,2023-04-02 12:27:18,311,335.39,"[-0.74, 1.63, -0.33]",18,67,69,94,187,1.820275
18411,18411,40.441630,-79.941353,323.4,1.796,2023-04-02 12:27:18,411,335.78,"[-0.73, 1.63, -0.33]",18,66,69,94,186,1.816232
18511,18511,40.441579,-79.941334,322.6,1.776,2023-04-02 12:27:18,511,336.14,"[-0.71, 1.62, -0.33]",18,64,67,94,186,1.799278
18611,18611,40.441524,-79.941311,321.8,1.751,2023-04-02 12:27:18,611,336.26,"[-0.7, 1.6, -0.33]",18,61,64,94,186,1.777329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407697,407697,40.441874,-79.941486,278.2,0.000,2023-04-02 12:33:48,697,66.15,"[0.02, 0.0, 0.0]",3,3,4,74,68,0.020000
407797,407797,40.441874,-79.941486,278.2,0.000,2023-04-02 12:33:48,797,66.15,"[0.02, 0.0, -0.03]",3,3,4,74,68,0.036056
407897,407897,40.441874,-79.941487,278.2,0.000,2023-04-02 12:33:48,897,66.15,"[0.01, 0.0, -0.03]",3,3,4,74,68,0.031623
407997,407997,40.441874,-79.941487,278.2,0.000,2023-04-02 12:33:48,997,66.15,"[0.02, 0.01, -0.02]",3,3,4,74,68,0.030000
408097,408097,40.441874,-79.941487,278.2,0.000,2023-04-02 12:33:48,97,66.15,"[0.03, 0.01, 0.0]",3,3,4,74,68,0.031623

## Load Drive

### Fit

In [39]:
import os

def transform_fit_path(path):
    parts = path.split('/')
    folder = parts[-3].split("_")[0] + ('_r' if '_r_' in parts[-3] else '')
    folder = {'inviscid': 'Inviscid', 'seraph': 'Seraph', 'zuke': 'Zuke', 'kp': 'KP', 
              'seraph_r': 'Seraph_r', 'zuke_r': 'Zuke_r'}[folder]
    return f"{folder}/GMetrix/{parts[-1]}"
fit = [(p, transform_fit_path(p)) for p in glob.glob(f"/mnt/d/2023-24/Virb Backups/*/GMetrix/*.fit")]
len(fit)

2656

In [40]:
seen = set()
missing = []
for raw, p in fit:
  if p in seen:
    continue
  seen.add(p)
  if not os.path.exists(f"{DATA_PATH}/archive/{p}"):
    missing.append((raw, p))
len(missing)

992

In [43]:
import shutil
for raw, p in tqdm(missing):
    shutil.copy(raw, f"{DATA_PATH}/archive/{p}")

  0%|          | 0/992 [00:00<?, ?it/s]

### Media

In [ ]:
# DATA_PATH = '/mnt/d/tmp'

In [4]:
import os
import shutil
def transform_media_path(path):
    parts = path.split('/')
    folder = parts[-4].split("_")[0] + ('_r' if '_r_' in parts[-4] else '')
    folder = {'inviscid': 'Inviscid', 'seraph': 'Seraph', 'zuke': 'Zuke', 'kp': 'KP', 
              'seraph_r': 'Seraph_r', 'zuke_r': 'Zuke_r'}[folder]
    return f"{folder}/DCIM/{parts[-2]}/{parts[-1]}"

media = [(p, transform_media_path(p)) for p in glob.glob(f"/mnt/d/2023-24/Virb Backups/*/DCIM/*/*") if not p.endswith('.MP4')]

In [5]:
seen = set()
missing = []
for raw, p in media:
  if p in seen:
    continue
  seen.add(p)
  if not os.path.exists(f"{DATA_PATH}/archive/{p}"):
    missing.append((raw, p))
len(missing)

541

In [6]:
total_size = 0
for raw, p in tqdm(missing):
    total_size += os.path.getsize(raw)
print(f"Total size of missing media files: {total_size / (1024 * 1024 * 1024):.2f} GB")

  0%|          | 0/541 [00:00<?, ?it/s]

Total size of missing media files: 72.08 GB

In [12]:
for raw, p in tqdm(missing):
    os.makedirs(f"{DATA_PATH}/archive/{'/'.join(p.split('/')[:-1])}", exist_ok=True)
    shutil.copy(raw, f"{DATA_PATH}/archive/{p}")

  0%|          | 0/541 [00:00<?, ?it/s]

KeyboardInterrupt: